#!/usr/bin/env python3
import requests
import re
import json
import time
import os
import sys
from datetime import datetime
from colorama import Fore, Style
from urllib.parse import urlparse

# Disable SSL warnings
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

class WAFDetector:
    def __init__(self, target, timeout=10, output=None, realtime_callback=None):
        """
        Initialize the WAF detector
        
        Args:
            target (str): Target URL
            timeout (int): Request timeout in seconds
            output (str): Output file path
            realtime_callback (function): Callback function for real-time reporting of detected WAFs
        """
        self.target = target
        self.timeout = timeout
        self.output = output or f"results_waf_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
        self.realtime_callback = realtime_callback
        self.session = requests.Session()
        self.waf_detected = False
        self.detected_wafs = []
        
        # Normalize the target URL
        if not self.target.startswith(('http://', 'https://')):
            self.target = 'https://' + self.target.strip('/')
        else:
            self.target = self.target.strip('/')
        
        # Parse the target URL
        self.parsed_url = urlparse(self.target)
        self.domain = self.parsed_url.netloc
        
        # Load WAF signatures
        self.signatures = self._load_signatures()
        
        # Session configuration
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
            'Accept-Language': 'en-US,en;q=0.5',
            'Accept-Encoding': 'gzip, deflate',
            'Connection': 'close',
            'Upgrade-Insecure-Requests': '1',
            'Cache-Control': 'no-cache',
            'Pragma': 'no-cache'
        })
    
    def _load_signatures(self):
        """Load WAF signatures"""
        # Common WAF signatures
        return {
            "Cloudflare": {
                "headers": ["cf-ray", "cloudflare", "__cfduid", "cf-cache-status"],
                "body": ["cloudflare-nginx", "cloudflare ray id", "attention required! | cloudflare", "sorry, you have been blocked", "pardon our interruption"]
            },
            "AWS WAF": {
                "headers": ["x-amz-cf-id", "x-amz-id"],
                "body": ["aws-waf-error", "aws", "amazon web services"]
            },
            "Akamai": {
                "headers": ["x-akamai-transformed", "akamai-origin-hop"],
                "body": ["akamai", "reference #"]
            },
            "Imperva Incapsula": {
                "headers": ["incap_ses", "_incapsula_"],
                "body": ["incapsula", "incapsula incident", "powered by incapsula"]
            },
            "Sucuri": {
                "headers": ["x-sucuri-id", "x-sucuri-cache"],
                "body": ["sucuri website firewall", "access denied - sucuri website firewall"]
            },
            "Fastly": {
                "headers": ["fastly-io-info", "x-fastly", "fastly-ssl"],
                "body": ["fastly", "fastly error"]
            },
            "ModSecurity": {
                "headers": ["mod_security", "mod_security_crs"],
                "body": ["mod_security", "not acceptable", "403 forbidden", "error 403"]
            },
            "F5 BIG-IP ASM": {
                "headers": ["bigsiteid", "bigipserver", "x-cnection", "x-wa-info"],
                "body": ["request rejected", "the requested url was rejected", "f5 networks"]
            },
            "Citrix NetScaler AppFirewall": {
                "headers": ["citrix_ns_id", "ns-cache", "citrix-application"],
                "body": ["citrix application firewall", "ns_af", "netscaler"]
            },
            "Wordfence": {
                "headers": [],
                "body": ["wordfence", "generated by wordfence", "site access is blocked", "wordfence security"]
            },
            "Fortinet FortiWeb": {
                "headers": ["fortigate", "fortiweb"],
                "body": ["fortinet", "fortigate", "fortiweb"]
            },
            "Barracuda": {
                "headers": ["barracuda", "barra_counter"],
                "body": ["barracuda networks", "barracuda application server", "barracuda application firewall"]
            },
            "DDoS-Guard": {
                "headers": ["ddos-guard"],
                "body": ["ddos-guard", "ddg-endpoint"]
            },
            "Radware AppWall": {
                "headers": ["x-sl-compstate"],
                "body": ["unauthorized activity has been detected", "additional information", "radware", "appwall"]
            },
            "Wallarm": {
                "headers": ["wallarm", "nginx-wallarm"],
                "body": ["wallarm", "owasp wallarm", "nginx-wallarm"]
            },
            "Comodo WAF": {
                "headers": ["protected by comodo"],
                "body": ["protected by comodo", "comodo", "cwatch"]
            }
        }
    
    def _make_request(self, path="", method="GET", params=None, data=None, headers=None, cookies=None):
        """Make a request to the target website with error handling"""
        try:
            url = self.target
            if path:
                url = f"{self.target}/{path.lstrip('/')}"
            
            custom_headers = self.session.headers.copy()
            if headers:
                custom_headers.update(headers)
            
            response = self.session.request(
                method=method,
                url=url,
                params=params,
                data=data,
                headers=custom_headers,
                cookies=cookies,
                timeout=self.timeout,
                verify=False,
                allow_redirects=True
            )
            return response
        except requests.exceptions.RequestException:
            return None
    
    def _check_baseline(self):
        """Check the baseline response without malicious payloads"""
        print(f"{Fore.CYAN}[*] Checking baseline response for {self.target}{Style.RESET_ALL}")
        
        baseline = self._make_request()
        if not baseline:
            print(f"{Fore.RED}[!] Could not connect to {self.target}{Style.RESET_ALL}")
            return None
        
        print(f"{Fore.GREEN}[+] Connected to {self.target} (Status: {baseline.status_code}){Style.RESET_ALL}")
        return baseline
    
    def _check_waf_signatures(self, response):
        """Check for WAF signatures in the response"""
        detected = []
        
        if not response:
            return detected
        
        # Convert headers and body to lowercase for case-insensitive comparison
        headers_text = str(response.headers).lower()
        body_text = response.text.lower()
        
        # Check each WAF signature
        for waf_name, signature in self.signatures.items():
            # Check headers
            for header_pattern in signature["headers"]:
                if header_pattern.lower() in headers_text:
                    detected.append(waf_name)
                    break
            
            # If not already detected in headers, check body
            if waf_name not in detected:
                for body_pattern in signature["body"]:
                    if body_pattern.lower() in body_text:
                        detected.append(waf_name)
                        break
        
        return detected
    
    def _check_waf_behavior(self):
        """
        Test the website with payloads that might trigger WAF responses
        Returns list of detected WAFs and a generic WAF detection flag
        """
        print(f"{Fore.CYAN}[*] Testing with malicious payloads to detect WAF behavior{Style.RESET_ALL}")
        
        # Common attack signatures that often trigger WAFs
        payloads = [
            {
                "description": "SQL Injection",
                "path": "?id=1' OR 1=1--",
                "headers": {}
            },
            {
                "description": "XSS Attack",
                "path": "?q=<script>alert(1)</script>",
                "headers": {}
            },
            {
                "description": "Local File Inclusion",
                "path": "?file=../../../etc/passwd",
                "headers": {}
            },
            {
                "description": "Command Injection",
                "path": "?cmd=cat%20/etc/passwd",
                "headers": {}
            },
            {
                "description": "User-Agent Scanner",
                "path": "",
                "headers": {"User-Agent": "sqlmap/1.4.7"}
            },
            {
                "description": "Bad Bot",
                "path": "",
                "headers": {"User-Agent": "nikto/2.1.6"}
            },
            {
                "description": "OWASP ModSecurity Test",
                "path": "?test=/bin/sh",
                "headers": {"Content-Type": "application/x-www-form-urlencoded", "X-Scan": "1"}
            }
        ]
        
        # Get the baseline response
        baseline = self._check_baseline()
        if not baseline:
            return [], False
        
        baseline_status = baseline.status_code
        baseline_content_type = baseline.headers.get('Content-Type', '')
        baseline_headers = baseline.headers
        baseline_body_length = len(baseline.text)
        baseline_server = baseline_headers.get('Server', 'Unknown')
        
        # Detected WAFs
        detected = []
        # First check the baseline for WAF signatures
        baseline_wafs = self._check_waf_signatures(baseline)
        detected.extend(baseline_wafs)
        
        # Initialize real-time reporting
        if self.realtime_callback:
            self.realtime_callback({
                "type": "baseline",
                "status": baseline_status,
                "server": baseline_server,
                "detected_wafs": baseline_wafs
            })
        
        # Check response behavior to malicious payloads
        generic_waf_detected = False
        
        for payload in payloads:
            print(f"{Fore.CYAN}[*] Testing payload: {payload['description']}{Style.RESET_ALL}")
            
            if self.realtime_callback:
                self.realtime_callback({
                    "type": "testing",
                    "payload": payload['description']
                })
            
            time.sleep(1)  # Avoid rate limiting
            
            response = self._make_request(
                path=payload["path"],
                headers=payload["headers"]
            )
            
            if not response:
                continue
            
            # Check for WAF signatures specific to this payload
            waf_sigs = self._check_waf_signatures(response)
            for waf in waf_sigs:
                if waf not in detected:
                    detected.append(waf)
                    print(f"{Fore.GREEN}[+] Detected {waf} based on signature in response to {payload['description']}{Style.RESET_ALL}")
                    
                    if self.realtime_callback:
                        self.realtime_callback({
                            "type": "waf_detected",
                            "waf": waf,
                            "payload": payload['description']
                        })
            
            # Check for behavioral changes that might indicate a generic WAF
            status_changed = response.status_code != baseline_status
            server_changed = response.headers.get('Server', 'Unknown') != baseline_server
            size_ratio = len(response.text) / baseline_body_length if baseline_body_length > 0 else 0
            
            # Common WAF behavior - block with 403 or similar
            if status_changed and response.status_code in [400, 403, 405, 406, 429, 500, 501, 502, 503]:
                generic_waf_detected = True
                print(f"{Fore.YELLOW}[!] Possible WAF detected - response status changed to {response.status_code} for {payload['description']}{Style.RESET_ALL}")
                
                if self.realtime_callback:
                    self.realtime_callback({
                        "type": "anomaly",
                        "anomaly_type": "status_change",
                        "baseline": baseline_status,
                        "current": response.status_code,
                        "payload": payload['description']
                    })
            
            # Check for significant content length change
            if not generic_waf_detected and (size_ratio < 0.7 or size_ratio > 1.3):
                generic_waf_detected = True
                print(f"{Fore.YELLOW}[!] Possible WAF detected - response size changed significantly for {payload['description']}{Style.RESET_ALL}")
                
                if self.realtime_callback:
                    self.realtime_callback({
                        "type": "anomaly",
                        "anomaly_type": "size_change",
                        "baseline": baseline_body_length,
                        "current": len(response.text),
                        "payload": payload['description']
                    })
            
            # Check for server header changes
            if not generic_waf_detected and server_changed:
                generic_waf_detected = True
                print(f"{Fore.YELLOW}[!] Possible WAF detected - server header changed for {payload['description']}{Style.RESET_ALL}")
                
                if self.realtime_callback:
                    self.realtime_callback({
                        "type": "anomaly",
                        "anomaly_type": "server_change",
                        "baseline": baseline_server,
                        "current": response.headers.get('Server', 'Unknown'),
                        "payload": payload['description']
                    })
            
            # Look for specific error messages commonly used by WAFs
            if not generic_waf_detected:
                waf_keywords = [
                    "forbidden", "waf", "blocked", "security", "protect",
                    "incident", "denied", "ip", "captcha", "suspicious", "unauthorized",
                    "attack", "detected", "malicious", "violation", "threat", "access denied",
                    "your request has been blocked", "your ip has been blocked"
                ]
                
                for keyword in waf_keywords:
                    if keyword in response.text.lower():
                        generic_waf_detected = True
                        print(f"{Fore.YELLOW}[!] Possible WAF detected - found keyword '{keyword}' in response for {payload['description']}{Style.RESET_ALL}")
                        
                        if self.realtime_callback:
                            self.realtime_callback({
                                "type": "anomaly",
                                "anomaly_type": "keyword",
                                "keyword": keyword,
                                "payload": payload['description']
                            })
                        break
        
        # If we detected a generic WAF but couldn't identify it, add to the list
        if generic_waf_detected and not detected:
            detected.append("Generic WAF")
            if self.realtime_callback:
                self.realtime_callback({
                    "type": "waf_detected",
                    "waf": "Generic WAF",
                    "payload": "multiple"
                })
        
        return detected, generic_waf_detected
    
    def run(self):
        """Run the WAF detection tests"""
        print(f"{Fore.CYAN}[*] Starting WAF detection for {self.target}{Style.RESET_ALL}")
        print(f"{Fore.CYAN}[*] Results will be saved to {self.output}{Style.RESET_ALL}")
        
        # Create output file with header
        with open(self.output, "w") as f:
            f.write(f"# WAF Detection Results for {self.target}\n")
            f.write(f"# Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        
        # Run the WAF detection tests
        detected_wafs, generic_waf_detected = self._check_waf_behavior()
        self.detected_wafs = detected_wafs
        self.waf_detected = generic_waf_detected or len(detected_wafs) > 0
        
        # Display and save results
        print("\n" + "=" * 60)
        print(f"{Fore.CYAN}[*] WAF Detection Results for {self.target}{Style.RESET_ALL}")
        print("=" * 60)
        
        # Save detailed results
        with open(self.output, "a") as f:
            if self.waf_detected:
                if detected_wafs:
                    waf_list = ", ".join(detected_wafs)
                    print(f"{Fore.GREEN}[+] WAF Detected: {waf_list}{Style.RESET_ALL}")
                    f.write(f"WAF Detected: {waf_list}\n")
                    
                    for waf in detected_wafs:
                        f.write(f"- {waf}\n")
                else:
                    print(f"{Fore.YELLOW}[!] Generic WAF Detected (Type Unknown){Style.RESET_ALL}")
                    f.write("Generic WAF Detected (Type Unknown)\n")
                    f.write("- The website appears to be protected by a WAF, but the specific type could not be identified.\n")
                    f.write("- The protection was detected based on behavior analysis of responses to malicious payloads.\n")
            else:
                print(f"{Fore.YELLOW}[!] No WAF Detected{Style.RESET_ALL}")
                f.write("No WAF Detected\n")
                f.write("- The website does not appear to be protected by a WAF.\n")
                f.write("- Note: Some sophisticated WAFs may not be detected by this tool.\n")
        
        print(f"{Fore.GREEN}[+] Results saved to {self.output}{Style.RESET_ALL}")
        
        # Return results
        return {
            "waf_detected": self.waf_detected,
            "detected_wafs": self.detected_wafs
        }

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="WAF Detector - Detect Web Application Firewalls")
    parser.add_argument("target", help="Target URL (e.g., http://example.com)")
    parser.add_argument("--timeout", help="Request timeout in seconds", type=int, default=10)
    parser.add_argument("-o", "--output", help="Output file path", default=None)
    
    args = parser.parse_args()
    
    detector = WAFDetector(
        target=args.target,
        timeout=args.timeout,
        output=args.output
    )
    
    detector.run() 